spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hirepoint
spring.datasource.username=postgres
spring.datasource.password=Begli2007!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.file.name=logs/hirepoint.log
logging.level.com.begli.hirepoint=INFO